title: Voer een AI-imagegenerator uit op jouw Raspberry Pi
hero_image: images/banner.png
description: Installeer en voer een Stable Diffusion AI-imagegeneratiemodel uit op jouw Raspberry Pi-computer!
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Wat ga je maken
  - 
    title: Installeer het model op jouw Raspberry Pi
    completion:
      - engaged
  - 
    title: Voer het script uit
    completion:
      - internal
  - 
    title: Wat kun je nu doen?
    completion:
      - external
