project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /en/**/*.*
    ignore:
      - /en/**/*.pdf
      - /en/**/*.mp3
      - /en/**/*.zip
    translation: /%locale%/**/%original_file_name%
