title: Ejecuta un generardo de imágenes IA en tu Raspberry PI
hero_image: images/banner.png
description: '¡Instala y ejecuta un modelo de generación de imágenes de IA Stable Diffusion en tu computadora Raspberry Pi!'
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Lo que harás
  - 
    title: Instala el modelo en tu Raspberry Pi
    completion:
      - engaged
  - 
    title: Ejeuta el script
    completion:
      - external
